metadata:
    org:
        id: "3053"
        handle: charukakarunanayake
    displayName: test_component_2
    displayType: ballerinaService
    description: Hehe
    version: 1.0.0
    projectId: 58f8921e-64c4-491d-b590-f9d4c39dc5e2
    accessibility: external
    repository:
        appSubPath: test_component_2
        orgApp: CharukaK
        nameApp: TestCP3
        branchApp: main
        gitProvider: github
id: 11153c34-75a2-44b3-86e8-5e69d9612dea
handler: yebcps
commitHash: ""
